### ISSUE TITLE
no response from the sensor

### ISSUE THREAD

**Issue by AdnanAhmed97** [Bee-Mar/MMM-Simple-Swiper#1]
I followed all the instructions as in the readme but when i ran the mirror there is no response and in the terminal i was popped up with an error called no main js file. Hence i had to rename the main js file and the error disappeared but still nothings working.
Thanks for replying!

**Comment by Bee-Mar** [comment]
I'll be making an instructional video today. It will begin with a fresh installation of Raspbian, MagicMirror, and everything else you'll need. I'll leave this issue open until the video is posted, and you're able to get the module working.

**Comment by AdnanAhmed97** [comment]
Thanks a lot!
Ive been looking for this swipe feature for a long time and found yours was the simplest and easiest thanks for the module!

**Comment by Bee-Mar** [comment]
Well, hopefully it'll work as well for you as it did for me!

**Comment by AdnanAhmed97** [comment]
Thanks again!
Till what time will the video be up?

**Comment by Bee-Mar** [comment]
Hopefully within a couple hours. Three to four at the most.

**Comment by Bee-Mar** [comment]
Well, embarrassingly, I believe the root cause of the issue was that I stupidly uploaded the file with the wrong casing in the name. I'll be posting the video soon, as well a detailed installation guide. The guide is written, and will be posted, as soon as I use it to walk through the installation once more. I want to make sure it's crystal clear, and can be understood easily.

**Comment by Bee-Mar** [comment]
Alright, all the content, along with a video is posted on the repo. Hopefully it helps!

**Comment by AdnanAhmed97** [comment]
Thanks!
It works like a charm!

**Comment by Bee-Mar** [comment]
perfect!
