### ISSUE TITLE
Page is automatically changing on it's own

### ISSUE THREAD

**Issue by sanj234** [Bee-Mar/MMM-Simple-Swiper#3]
I followed the instructions and worked perfectly until I ran the Magic Mirror and found that my Calander is missing and my pages are toggling on their own. Please help :/

**Comment by Bee-Mar** [comment]
Have you attempted to change the `delay` value within your config file? Have you attempted to adjust the position of the sensors? Because they're ultra-sonic sensors, the surroundings can play a part in their behavior. Try adjusting the spacing between them, and where you're sensors are facing. Also, where did you place your Calendar? Try placing your `Calendar` in the `excludes` section of your config.
